### ISSUE TITLE
I have some problem for the surface distortion

### ISSUE THREAD

**Issue by Jaywen1** [yuchendoudou/TODE#1]
Hi Chen：
     期待小半年，非常感谢您的开源工作！
     我在使用您提供的checkpoints生成云图时遇到了一点小问题，即发现推测透明物表面存在一定程度畸变，可能会对下游任务（比如模板点云的配准等）造成影响，请问您有遇到过这样问题或该如何尝试地去解决它吗？盼望您的回复，谢谢！

另外下面两行似乎有点小的bug
①inference.py中99行,应该是只有一个输出depth_res;
②builder.py 中第460行，应该是“checkpoints”；

![TODE](https://user-images.githubusercontent.com/86770537/229368499-eb46a7f0-3506-4fba-92f2-ffc40852f1e8.png)

**Comment by yuchendoudou** [comment]
首先多谢提出这两个bug
对于你的问题：
我们这个模型主要是为了方便后续的机械臂抓取的，所以有一定程度的畸变对于机械臂抓取并没有太大的影响。对于你们点云配准的话，如果你们的透明物体是比较规则的，我感觉你可以考虑对生成的深度进行一定的平滑滤波操作来方便你的使用。

**Comment by Jaywen1** [comment]
> 首先多谢提出这两个bug 对于你的问题： 我们这个模型主要是为了方便后续的机械臂抓取的，所以有一定程度的畸变对于机械臂抓取并没有太大的影响。对于你们点云配准的话，如果你们的透明物体是比较规则的，我感觉你可以考虑对生成的深度进行一定的平滑滤波操作来方便你的使用。

哈哈，谢谢！我刚刚也想可以尝试对深度图做平滑看看
