### ISSUE TITLE
关于对于transCG数据集测试的metrics存在差异问题

### ISSUE THREAD

**Issue by Jaywen1** [yuchendoudou/TODE#2]
您好，
通过学习您的文章受益匪浅，但是我用您提供的checkpoints在TODE网络上测试transCG数据集上时，发现结果与文中存在较大的差异，请问这个checkpoints是否对应当前的模型，期待您的回复，谢谢！

                                                         

[__main__][INFO]  Building models ... (test.py:40)
Building Encoder-Decoder model..Done.
[__main__][INFO]  Building dataloaders ... (test.py:47)
[utils.builder][INFO]  Load transcg dataset as testing set with 23524 samples. (builder.py:231)
[__main__][INFO]  Checking checkpoints ... (test.py:50)
[__main__][INFO]  Checkpoint stats/train-tg-val-tg/checkpoint.tar (epoch 35) loaded. (test.py:57)
[__main__][INFO]  Start testing process. (test.py:65)
Time: 0.0171s: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2940/2940 [04:04<00:00, 12.00it/s]
[__main__][INFO]  Finish testing process, average running time: 0.0207s (test.py:83)
[utils.metrics][INFO]  Metrics on 23520 samples: (functions.py:30)
[utils.metrics][INFO]    MaskedMSE: 0.002039 (functions.py:33)
[utils.metrics][INFO]    MaskedRMSE: 0.037516 (functions.py:33)
[utils.metrics][INFO]    MaskedREL: 0.065663 (functions.py:33)
[utils.metrics][INFO]    MaskedMAE: 0.029952 (functions.py:33)
[utils.metrics][INFO]    MaskedThreshold@1.05: 60.569659 (functions.py:33)
[utils.metrics][INFO]    MaskedThreshold@1.10: 75.405508 (functions.py:33)
[utils.metrics][INFO]    MaskedThreshold@1.25: 97.370865 (functions.py:33)

**Comment by yuchendoudou** [comment]
不好意思，这个checkpoint不是最终的checkpoint，由于名字太像上传错了，新的已经上传

**Comment by yuchendoudou** [comment]
transcg的checkpoint已经上传

**Comment by Jaywen1** [comment]
再次打搅您一下，通过拜读您的论文，swin-Transformer+FFM的确比DFnet的denseBlock更有优势。
但是在您原论文的 Table 1中，在CG中的训练，测试时对CG中未见过的objects比见过的表现还好，这里是不是写反了呀？




文杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuchendoudou/TODE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 上午8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuchendoudou/TODE] 关于对于transCG数据集测试的metrics存在差异问题 (Issue #2)





 
transcg的checkpoint已经上传

**Comment by yuchendoudou** [comment]
没写反，因为cg训练数据集为人工制造的数据集，我们在训练的时候对数据集加了一定的人为噪声，这个人为噪声加上去后使得透明物体部分的深度图和实际的深度图相对接近，这个使得他的泛化性相对来说更好一点，如果去掉这个噪声就没有这个效果了，并且在测试集上性能也会下降。

**Comment by Jaywen1** [comment]
原来如此，我后面在您的提供的代码里找到了一个叫做handl_depth2函数。
我一直想的是对合成的rgb图作处理，而保持深度图不变以保证深度值的100%准确，您这个方式对我启发不少，我再好好想一想。


谢谢您！







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月18日(周二) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [yuchendoudou/TODE] 关于对于transCG数据集测试的metrics存在差异问题 (Issue #2)




 
没写反，因为cg训练数据集为人工制造的数据集，我们在训练的时候对数据集加了一定的人为噪声，这个人为噪声加上去后使得透明物体部分的深度图和实际的深度图相对接近，这个使得他的泛化性相对来说更好一点，如果去掉这个噪声就没有这个效果了，并且在测试集上性能也会下降。
