### ISSUE TITLE
Some questions about training the cg dataset.

### ISSUE THREAD

**Issue by Candice54** [yuchendoudou/TODE#3]
Dear Chen,
I really appreciate your opened the codes.
When I use the  ClearGrasp dataset to train the TODE network, I still cannot reach the effect in the paper. May I ask what I should do to have a better effect？In addition, I have some questions about hyperparameters.
1st,the combined_beta is set to 0.01 in the paper, but 0.1 in the default.yaml(Line 53).
2nd.some of the functions in the data_preparation.py don't seem to be used, such as dropout_random_ellipses_4corruptmask or add_noise_to_depth,and there are no “noise_params“ in the configuration file.
appreciate your reply！

**Comment by yuchendoudou** [comment]
Please use [train_cgsyn+ood_val_cgreal.yaml](https://github.com/yuchendoudou/TODE/blob/main/configs/train_cgsyn%2Bood_val_cgreal.yaml)
