### ISSUE TITLE
The TransCG dataset is not well trained

### ISSUE THREAD

**Issue by CasparZhao** [yuchendoudou/TODE#4]
Dear Chen,
When I trained the transcg dataset, the threshold was 1.05, the highest accuracy rate was only 70%, and the accuracy rate always dropped after the first five rounds of training, and it has remained at about 60%, is there any hyperparameter that needs to be modified during training?

**Comment by yuchendoudou** [comment]
I used [train_transcg_val_transcg.yaml](https://github.com/yuchendoudou/TODE/blob/main/configs/train_transcg_val_transcg.yaml) to train transcg. No hyperparameters need to be modified
