### ISSUE TITLE
Testing pre-trained model on real-life dataset

### ISSUE THREAD

**Issue by pranavgundewar** [yuchendoudou/TODE#6]
Hi! Thank you for sharing your work. I would like to test the model by inputting RGB and Depth images from Kinect camera and carry out the inference. What setting and scripts should be used?

**Comment by yuchendoudou** [comment]
Sorry for long time. Please check https://github.com/yuchendoudou/TODE/blob/main/utils/data_preparation.py and set the parameters with your camera.
