### ISSUE TITLE
Not able to reproduce the results in paper.

### ISSUE THREAD

**Issue by iitaakash** [yuchendoudou/TODE#7]
I tried `python train.py -c ./configs/train_transcg_val_transcg.yaml` and did not get results even close to the one mentioned in paper. The model is not training properly !

**Comment by yuchendoudou** [comment]
Sorry for this problem. Please set “use_depth_augument” to False and train again.

**Comment by iitaakash** [comment]
Thanks ! After training for 40 epochs. I am getting the paper result close to the epoch 15.
